### ISSUE TITLE
Update to Jasmine 2.0

### ISSUE THREAD

**Issue by almai** [tsteur/titanium-alloy-jasmine-testing#1]
Hi, do you plan to update to Jasmine 2.0 or don't you maintain the repo anymore? Alex

**Comment by tsteur** [comment]
I'll have a look how much work it is. Generally I am still maintaining it but didn't have a need for it recently

**Comment by tsteur** [comment]
Updated... Would you mind having a look and reopen in case it does not work for you? Note: The output is a little bit different as I am using the Jasmine Console Reporter now.

**Comment by almai** [comment]
Thomas,

that was ligthning fast! Thank you very much! I'll have a look at it soon but it'll take some time. 

I'm new to Titanium programming.In the moment I'm trying to find the right setup to start. I'm coming from the Ruby world and am used to TDD and BDD. There you have all these great tools like RSpec, Schoulda, Mocka, Factory Girl and Cucumber and if you are used to the process of TDD you don't want to go without it anymore. So before I get any further I want to make sure that I have at least to opportunity to implement it.

Jasmine looks very familiar to me and is promising. So I'll give it a try for sure. Do you have any other recommendations for me to look at in order to implement TDD in my Titanium programming process. Any source of information you could point me to would be very appreciated.

Thanks, Alex

**Comment by tsteur** [comment]
You could have a look at https://github.com/tonylukasavage/ti-mocha as well which uses mocha as a testing framework. I haven't used it so far and also no clue about the requirements. For me it was important that it is possible to run without any iOS SDK / Android SDK / on any platform as it is slower to run the tests within a simulator and it was important for me to let the tests run on Travis automatically after each commit.

**Comment by almai** [comment]
Thank you for this hint. I will check it out.

So, as I understood, you use only Jasmine for unit testing, don't you? Do you use any other tools like TestFlight or UIAutomation for itegration tests?

**Comment by tsteur** [comment]
I use Jasmine for unit testing and TestFlight to distribute releases to testers before an update goes to the App Store. I don't have any "integration tests". Otherwise I use the titanium-cli to integrate Titanium into any IDE instead of using Titanium Studio, see some examples here: https://github.com/piwik/piwik-mobile-2/blob/master/tools/deploy . You might be also interested in my eBook "Titanium Mobile - Multi Platform Apps mit JavaScript" (German) which is available for instance on Amazon or iTunes. It also covers Alloy a little bit. Additional resources can be found for instance here: http://www.tidev.io/

**Comment by almai** [comment]
Thomas, noch mal Danke für deine Geduld. Du hast mir sehr weiter geholfen. Ich werde mir dein Buch noch heute auf meinen Kindle ziehen. Alex
